### ISSUE TITLE
Update LibWebRTC to 1.0.0

### ISSUE THREAD

**Issue by aisouard** [aisouard/node-webrtc#11]
I finally released the first stable version of LibWebRTC.
I'll resume the progress of node-webrtc by using the 1.0.0 release located there: https://github.com/aisouard/libwebrtc/releases/tag/v1.0.0

**Comment by clemos** [comment]
How should we do that ?

**Comment by aisouard** [comment]
Just have to edit that line: https://github.com/aisouard/node-webrtc/blob/develop/package.json#L25
I use the issue tracker like a todo list most of the time :)

**Comment by clemos** [comment]
It seems to work smoothly on my `develop` branch :)

**Comment by aisouard** [comment]
Got it!
It has been cherry-pick'd.
